services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - '3000:3000'
    volumes:
      - ./api:/app
      - app-node-modules:/app/node_modules

  blog:
    build: ./blog
    container_name: blog_c
    ports:
      - '5173:5173'
    volumes:
      - ./blog:/app
      - app-node-modules:/app/node_modules
    stdin_open: true
    tty: true
volumes:
  app-node-modules:
